### ISSUE TITLE
请问目录下的bilibili直播间模拟调试器如何使用？

### ISSUE THREAD

**Issue by bbqqpp** [VoidmatrixHeathcliff/DanmuGame#1]
启动DanmuUtil和DanmuGame进程后，使用模拟调试器模拟进入房间和发弹幕都没反应

**Comment by VoidmatrixHeathcliff** [comment]
能看下您游戏脚本内容吗？

**Comment by bbqqpp** [comment]
感谢，已经解决了，用模拟调试器发送了创建角色弹幕后，成功创建角色了，不过是否有print或者log之类的函数，方便测试打印呢

**Comment by VoidmatrixHeathcliff** [comment]
脚本使用lua 5.4编写，所有lua标准库都可以用
